content:
  - name: meta
    label: Meta
    type: file
    path: src/_data/meta.json
    fields:
      - name: navigation
        label: Navigation
        type: object
        list: true
        fields:
          - { name: label, label: Label, type: string }
          - { name: url, label: URL, type: string }
          - { name: symbol, label: Symbol, type: string }
  - name: home
    label: Home
    path: src/index.njk
    type: file
    fields:
      - { name: layout, hidden: true, type: string, default: home.njk }
  - name: music
    label: Music
    path: src/music.njk
    type: file
    fields:
      - { name: layout, hidden: true, type: string, default: music.njk }
      - { name: title, label: Title, type: string }
  - name: bio
    label: Bio
    path: src/bio.njk
    type: file
    fields:
      - { name: layout, hidden: true, type: string, default: bio.njk }
      - { name: title, label: Title, type: string }
      - {
          name: bio,
          label: Long Bio,
          type: rich-text,
          options: { format: html },
        }
  - name: contact
    label: Contact
    type: file
    path: src/contact.njk
    fields:
      - { name: layout, hidden: true, type: string, default: contact.njk }
      - { name: title, label: Title, type: string }
      - name: navigation
        label: Navigation
        type: object
        list: true
        fields:
          - { name: label, label: Label, type: string }
          - { name: url, label: URL, type: string }
          - { name: symbol, label: Symbol, type: string }
  - name: releases
    label: Releases
    path: src/releases
    type: collection
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date }
      - {
          name: type,
          label: Type,
          type: select,
          options: { values: [album, track] },
        }
      - { name: bandcampid, label: Bandcamp ID, type: number }