content:
  - name: home
    label: Home
    path: src/index.md
    type: file
    fields:
      - { name: title, label: Title, type: string }
      - { name: bio, label: Short Bio, type: rich-text }
      - { name: youtubeid, label: Youtube ID, type: string }
  - name: about
    label: About
    path: src/about.md
    type: file
    fields:
      - { name: title, label: Title, type: string }
      - { name: bio, label: Long Bio, type: rich-text }
  - name: releases
    label: Releases
    path: src/releases
    type: collection
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date }
      - { name: type, label: Type, type: select, options: { values: [album, track] } }
      - { name: bandcampid, label: Bandcamp ID, type: number }